import { cartData } from "@/lib/constant";
import { Metadata } from "next";
import Link from "next/link";
import * as React from "react";

export const metadata: Metadata = {
    title: "Cart | Ecommerce Design ",
    description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice | Cart Page",
};
export const dynamic = 'force-static'; //ssg becuase there is no dynamic data.

const Cart: React.FC = () => {
    return (
        <div className="p-4 max-w-4xl mx-auto">
            <p className="text-sm mb-4 text-gray-400">
                <Link href={'/'}>Home</Link> /  <span className="font-semibold text-gray-800"><Link href={'/cart'}>Cart</Link></span>
            </p>
            <div className="overflow-x-auto">
                <table className="w-full border-separate  border-spacing-y-4">
                    <thead className="border-y border-black text-left text-sm font-medium">
                        <tr>
                            <th className="p-4">Product</th>
                            <th className="p-4 text-center">Price</th>
                            <th className="p-4 text-center">Quantity</th>
                            <th className="p-4 text-center">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {cartData.items.map((item, index) => (
                            <tr key={index} className="bg-white border-y border-black shadow-sm">
                                <td className="p-4 flex items-center gap-4">
                                    <img
                                        src={item.imageSrc}
                                        alt={item.productName}
                                        className="w-12 h-12 object-cover rounded"
                                    />
                                    {item.productName}
                                </td>
                                <td className="p-4 text-center">{item.price}</td>
                                <td className="p-4 text-center">
                                    <input
                                        type="number"
                                        defaultValue={item.quantity}
                                        className="w-12 border rounded text-center"
                                    />
                                </td>
                                <td className="p-4 text-center">{item.subtotal}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>


            </div>

            <div className="flex flex-wrap justify-between mt-6 gap-4">
                <button className="px-6 py-3 border rounded border-gray-400 text-gray-700">
                    Return To Shop
                </button>
                <button className="px-6 py-3 border rounded border-gray-400 text-gray-700">
                    Update Cart
                </button>
            </div>

            <div className="flex flex-wrap mt-10 gap-6">
                <form className="flex flex-wrap gap-4">
                    <input
                        type="text"
                        placeholder="Coupon Code"
                        className="p-3 border rounded flex-1 h-12"
                    />
                    <button type="submit" className="px-6 py-3 h-12 bg-red-500 text-white rounded">
                        Apply Coupon
                    </button>
                </form>

                <div className="p-6 bg-white border rounded shadow-sm w-full max-w-sm">
                    <h2 className="text-lg font-medium mb-4">Cart Total</h2>
                    <div className="flex justify-between mb-2">
                        <span>Subtotal:</span>
                        <span>$1750</span>
                    </div>
                    <div className="border-t my-2"></div>
                    <div className="flex justify-between mb-2">
                        <span>Shipping:</span>
                        <span>Free</span>
                    </div>
                    <div className="border-t my-2"></div>
                    <div className="flex justify-between mb-2">
                        <span>Total:</span>
                        <span>$1750</span>
                    </div>
                    <Link href={'/checkout'}>
                        <button className="w-full mt-4 py-3 bg-red-500 text-white rounded">
                            Proceed to Checkout
                        </button>
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default Cart;
