import ProdcutList from "@/components/ProdcutList"
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "WishList | Ecommerce Design",
    description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice | Wishlist Page",
};
export const dynamic = 'force-static'; //ssg becuase there is no dynamic data.

const page = () => {

    return (
        <main className="flex flex-col items-cesnter justify-between mb-8 lg:px-14">
            <ProdcutList
                heading="Wishlist (4)"
                productSet={[9, 13]}
                btnText='Move All To Bag'
                isWishlistProduct={true}
                isTimer={false}
            />
            <ProdcutList
                heading="Just For You"
                btnText='See All'
                productSet={[5, 9]}
                isTimer={false}
            />

        </main>
    )
}

export default page
