import Link from 'next/link';
import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "My Account | Giaic Ecommerce Design ",
    description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice | Manage Account Page",
  };
  export const dynamic = 'force-static'; //ssg becuase there is no dynamic data.

const page = () => {
    const formData = {
        firstName: "Anas",
        lastName: "Ahmed",
        email: "anasahmedd244@gmail.com",
        address: "saddar, 75000, pakistan, Karachi"
    };

    const menuItems = [
        { text: "My Profile", isActive: true },
        { text: "Address Book" },
        { text: "My Payment Options" },
        { text: "My Returns" },
        { text: "My Cancellations" }
    ];
    return (
        <main className="flex justify-center flex-col px-6 sm:px-14">
            <p className="text-sm mb-4 ml-6 sm:ml-8 mt-8 text-gray-400">
                <Link href={'/'}>Home</Link> / <span className="font-semibold text-gray-800">My Account</span>
            </p>
            <div className="self-center mt-20 w-full max-w-[1170px] max-md:mt-10 max-md:max-w-full">
                <div className="flex gap-5 max-md:flex-col">
                    <nav className="flex flex-col w-[19%] max-md:ml-0 max-md:w-full" role="navigation">
                        <div className="flex flex-col items-start text-base font-medium text-black max-md:mt-10">
                            <div role="menubar">
                                <div>Manage My Account</div>
                                <div className="flex flex-col self-end mt-4">
                                    {menuItems.slice(0, 3).map((item, index) => (
                                        <MenuItem key={index} {...item} />
                                    ))}
                                </div>
                                <div className="mt-6">My Orders</div>
                                <div className="flex flex-col self-center mt-4">
                                    {menuItems.slice(3).map((item, index) => (
                                        <MenuItem key={index} {...item} />
                                    ))}
                                </div>
                                <div className="mt-4">My WishList</div>
                            </div>
                        </div>
                    </nav>

                    <main className="flex flex-col ml-5 w-[81%] max-md:ml-0 max-md:w-full" role="main">
                        <form className="flex overflow-hidden flex-col px-20 py-10 mx-auto w-full text-base bg-white rounded shadow-sm max-md:px-5 max-md:mt-10 max-md:max-w-full">
                            <h1 className="self-start text-xl font-medium leading-snug text-red-500">
                                Edit Your Profile
                            </h1>

                            <div className="flex flex-wrap gap-10 items-start mt-4 text-black max-md:max-w-full">
                                <InputField label="First Name" value={formData.firstName} />
                                <InputField label="Last Name" value={formData.lastName} />
                            </div>

                            <div className="flex flex-wrap gap-10 items-start mt-6 text-black max-md:max-w-full">
                                <InputField label="Email" value={formData.email} />
                                <InputField label="Address" value={formData.address} />
                            </div>

                            <div className="flex flex-col mt-6 text-black max-md:max-w-full">
                                <div className="flex flex-col max-w-full w-[710px]">
                                    <label htmlFor="current-password" className="mb-2">Password Changes</label>
                                    <input
                                        type="password"
                                        id="current-password"
                                        placeholder="Current Password"
                                        className="flex overflow-hidden px-4 py-3.5 rounded bg-neutral-100 w-full mb-4"
                                        aria-label="Current Password"
                                    />
                                    <input
                                        type="password"
                                        id="new-password"
                                        placeholder="New Password"
                                        className="flex overflow-hidden px-4 py-3.5 rounded bg-neutral-100 w-full mb-4"
                                        aria-label="New Password"
                                    />
                                    <input
                                        type="password"
                                        id="confirm-password"
                                        placeholder="Confirm New Password"
                                        className="flex overflow-hidden px-4 py-3.5 rounded bg-neutral-100 w-full"
                                        aria-label="Confirm New Password"
                                    />
                                </div>
                            </div>

                            <div className="flex gap-8 items-center self-end mt-6">
                                <button
                                    type="button"
                                    className="self-stretch my-auto text-black"
                                    aria-label="Cancel changes"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="gap-2.5 self-stretch px-12 py-4 my-auto font-medium bg-red-500 rounded text-neutral-50 max-md:px-5"
                                    aria-label="Save profile changes"
                                >
                                    Save Changes
                                </button>
                            </div>
                        </form>
                    </main>
                </div>
            </div>
        </main>
    )
}
const MenuItem = ({ text, isActive = false }:MenuItemProps) => {
    return (
        <div
            className={`mt-2 ${isActive ? 'text-red-500' : 'opacity-50'}`}
            role="menuitem"
            tabIndex={0}
        >
            {text}
        </div>
    );
}
const InputField = ({ label, value, className = "" }:AccountInputFieldProps) => {
    const inputId = `${label.toLowerCase().replace(/\s+/g, '-')}-input`;

    return (
        <div className={`flex flex-col min-w-[240px] w-[330px] ${className}`}>
            <label htmlFor={inputId} className="text-black mb-2">{label}</label>
            <div className="flex flex-col mt-2 max-w-full w-[330px]">
                <div className="flex overflow-hidden flex-col justify-center items-start px-4 py-3.5 rounded bg-neutral-100">
                    <input
                        type="text"
                        id={inputId}
                        value={value}
                        className="w-full bg-transparent opacity-50 outline-none"
                        aria-label={label}
                    />
                </div>
            </div>
        </div>
    );
}
export default page
