import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import { Footer } from "@/components/Footer";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home | Ecommerce Design ",
  description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black text-xs sm:text-sm text-center w-full p-2 text-white">
          Summer Sale For All Swim Suits And Free Express Delivery - OFF 50%! <span className=" font-semibold underline"><Link href={'/search'}>Shop Now</Link></span>
        </div>
        <main className="py-3">
          <Navigation />
          {children}
        </main>
        <Footer />
      </body>
    </html >
  );
}
