
// product data
export const productData = [
    {
      image: "/products/controller3.png",
      title: "Havic HV G-92 Gamepad",
      slug: "havic-hv-g-92-gamepad",
      currentPrice: 192,
      originalPrice: 213,
      desc: "PlayStation 5 Controller Skin High quality vinyl with air channel adhesive for easy bubble free install & mess free removal Pressure sensitive.",
      sizes: ['XS', 'S', 'M', 'L', 'Xl'],
      stock: 7,
      rating: 4,
      reviews: 150,
    },
    {
      discount: 35,
      image: "/products/Frame-612.png",
      title: "AK-900 Wired Keyboard",
      slug: "ak-900-wired-keyboard",
      currentPrice: 960,
      originalPrice: 1160,
      sizes: ['XL', 'L', "XXL"],
      stock: 4,
      rating: 5,
      reviews: 75,
    },
    {
      discount: 30,
      image: "/products/monitor.png",
      title: "IPS LCD Gaming Monitor",
      slug: "ips-lcd-gaming-monitor",
      currentPrice: 370,
      originalPrice: 400,
      sizes: ['S', 'M', "XS"],
      stock: 9,
      rating: 4,
      reviews: 99,
    },
    {
      discount: 25,
      image: "/products/chair.png",
      title: "S-Series Comfort Chair",
      slug: "s-series-comfort-chair",
      currentPrice: 375,
      originalPrice: 400,
      sizes: ['M', 'L', "X"],
      stock: 7,
      rating: 8,
      reviews: 99,
    },
    {
      image: "/products/pink-shirt.png",
      title: "The north coat",
      slug: "the-north-coat",
      currentPrice: 260,
      originalPrice: 360,
      sizes: ['S', 'L', "X"],
      stock: 2,
      rating: 5,
      reviews: 65,
    },
    {
      image: "/products/bookshelf.png",
      title: "Small BookShelf",
      slug: "small-bookShelf",
      currentPrice: 360,
      originalPrice: 0,
      sizes: ['S', "M", 'L', "X", 'XL', "XXL"],
      stock: 3,
      rating: 5,
      reviews: 65,
    },
    {
      image: "/products/purse.png",
      title: "Gucci daffle bag",
      slug: "gucci-daffle-bag",
      currentPrice: 960,
      originalPrice: 1160,
      sizes: ['S', "X", 'XL', "XXL"],
      stock: 6,
      rating: 4.2,
      reviews: 65,
    },
    {
      image: "/products/aio-coooler.png",
      title: "RGB CPU Liquid Cooler",
      slug: "rgb-cpu-liquid-cooler",
      currentPrice: 160,
      originalPrice: 170,
      sizes: ['S', "M", 'L', "XXL"],
      stock: 10,
      rating: 5,
      reviews: 65,
    },
    {
      image: "/products/dog-food.png",
      title: "Breed Dry Dog Food",
      slug: "breed-dry-dog-food",
      currentPrice: 100,
      originalPrice: 0,
      sizes: ["X", 'XL', "XXL"],
      stock: 1,
      rating: 3,
      reviews: 35,
    },
    {
      image: "/products/camera.png",
      title: "Canon EOS DSLR Camera",
      slug: "canon-eos-dslr-camera",
      currentPrice: 360,
      stock: 7,
      rating: 4,
      reviews: 95,
    },
    {
      image: "/products/laptop.png",
      title: "ASUS FHD Gaming Laptop",
      slug: "asus-fhd-gaming-laptop",
      currentPrice: 700,
      sizes: ['S', "XXL"],
      stock: 3,
      rating: 5,
      reviews: 232,
    },
    {
      discount: 40,
      image: "/products/controller.png",
      title: "HAVIT HV-G82 Gamepad",
      slug: "havit-hv-g82-gamepad",
      currentPrice: 120,
      originalPrice: 160,
      sizes: ['X', 'L', "S"],
      stock: 3,
      rating: 4,
      reviews: 88,
    },
    {
      image: "/products/kid-car.png",
      title: "Kid Electric Car",
      slug: "kid-electric-car",
      currentPrice: 960,
      stock: 8,
      rating: 5,
      reviews: 35,
      colors: ['#fa000d', '#ed2630']
    },
    {
      image: "/products/shoes.png",
      title: "Jr. Zoom Soccer cleats",
      slug: "jr-zoom-soccer-cleats",
      currentPrice: 1160,
      sizes: ['S', "M", "X", 'XL', "XXL"],
      stock: 3,
      rating: 8,
      reviews: 35,
      colors: ['#b3fa00', '#ed2630']
  
    },
    {
      image: "/products/controller2.png",
      title: "GP11 Shooter USB Controller",
      slug: "gp11-shooter-usb-controller",
      currentPrice: 660,
      sizes: ['S', "M", 'L'],
      stock: 2,
      rating: 4.5,
      reviews: 55,
      colors: ['#000000', '#ed2630']
  
    },
    {
      discount: 25,
      image: "/products/jackett.png",
      title: "Quilted Satin Jacket",
      slug: "quilted-satin-jacket",
      currentPrice: 660,
      sizes: ['S', "X", 'XL', "XXL"],
      stock: 4,
      rating: 4.5,
      reviews: 55,
      colors: ['#022e08', '#ed2630']
    },
    {
      image: "/perfume.png",
      title: "Curology Product Set",
      slug: "curology-product-set",
      currentPrice: 500,
      originalPrice: 0,
      stock: 8,
      rating: 4,
      reviews: 145,
    },
  ];
  
  
  
  // Grid Layot Banners
  export const gridBanners = [
    {
      title: "PlayStation 5",
      description: "Black and White version of the PS5 coming out on sale.",
      imageUrl: "/ps5.png",
      imageSize: 511,
      gridColumn: "span 2 / span 2",
      gridRow: "span 3 / span 3",
      ariaLabel: "Shop PlayStation 5 gaming console"
    },
    {
      title: "Women's Collections",
      description: "Featured woman collections that give you another vibe.",
      imageUrl: "/women.png",
      imageSize: 411,
      gridColumn: 'span 2 / span 2',
      gridRow: "",
      ariaLabel: "Shop Women's fashion collections"
    },
    {
      title: "Speakers",
      description: "Amazon Wireless Speakers",
      imageUrl: "/speaker.png",
      imageSize: 311,
      gridColumn: "span 1 / span 1",
      gridRow: '',
      ariaLabel: "Amazon Wireless Speakers",
  
    },
    {
      title: "Perfume",
      description: "GUCCI INSTANCE OUD EDP",
      imageUrl: "/perfume.png",
      imageSize: 311,
      gridColumn: "span 1 / span 1",
      gridRow: '',
      ariaLabel: "GUCCI INSTANCE OUD EDP",
    },
  ];