import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Checkout | Giaic Ecommerce Design ",
    description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice | Checkout Page",
  };
  export const dynamic = 'force-static'; //ssg becuase there is no dynamic data.

const page = () => {
    const products = [
        { image: "/products/monitor.png", name: "LCD Monitor", price: 650 },
        { image: "/products/controller.png", name: "H1 Gamepad", price: 1100 }
    ];

    const bankIcons = [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHX7h0I6s8TJsqxI7pLDR8yGLu450Ph71rpg&s",
        "/visa.png",
        "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqmWphmHOgdbKyx3lbEyEgF4i9rVyIATYLgtZYRJb4g1Cbj43D",
        "https://uploads.commoninja.com/searchengine/wordpress/nagad.png"
    ];

    return (
        <main className="flex flex-col px-6 lg:spx-14 justify-center items-center">
            <div className="flex flex-col w-full max-w-screen-lg mx-auto items-start mt-16 max-md:mt-10">
                <nav
                    className="flex flex-wrap gap-3 items-center text-sm text-black opacity-50">
                    <div>Account /</div>
                    <div>My Account /</div>
                    <div>Product /</div>
                    <div>View Cart /</div>
                    <div className="opacity-100">CheckOut</div>
                </nav>

                <h1 className="mt-10 text-4xl font-medium tracking-widest leading-none text-black text-center max-md:mt-6">
                    Billing Details
                </h1>

                <div className="flex flex-col lg:flex-row justify-between w-full mt-12 mb-24 gap-6 max-md:gap-10">
                    <form className="flex flex-col w-full lg:w-5/12">
                        <div className="flex flex-col text-base">
                            <div className="space-y-8">
                                <FormField label="First Name" required id="firstName" />
                                <FormField label="Company Name" id="companyName" />
                                <FormField label="Street Address" required id="streetAddress" />
                                <FormField label="Apartment, floor, etc. (optional)" id="apartment" />
                                <FormField label="Town/City" required id="city" />
                                <FormField label="Phone Number" required id="phone" type="tel" />
                                <FormField label="Email Address" required id="email" type="email" />
                            </div>

                            <div className="flex items-center mt-6">
                                <input
                                    type="checkbox"
                                    id="saveInfo"
                                    className="w-6 h-6"
                                    aria-label="Save information for faster checkout"
                                />
                                <label htmlFor="saveInfo" className="ml-2">
                                    Save this information for faster check-out next time
                                </label>
                            </div>
                        </div>
                    </form>

                    <div className="flex flex-col w-full lg:w-5/12">
                        <div className="flex flex-col text-base">
                            {products.map((product, index) => (
                                 <div key={index} className="flex gap-6 items-center max-md:max-w-full">
                                 <img
                                     loading="lazy"
                                     src={product.image}
                                     alt={product.name}
                                     className="object-contain shrink-0 self-stretch my-auto aspect-square w-[54px]"
                                 />
                                 <div className="flex gap-10 items-center self-stretch my-auto min-w-[240px]">
                                     <div className="self-stretch my-auto text-black">{product.name}</div>
                                     <div className="self-stretch my-auto text-black">${product.price}</div>
                                 </div>
                             </div>
                            ))}

                            <div className="flex flex-col mt-8 max-w-full w-[422px]">
                                <div className="flex flex-col w-full">
                                    <div className="flex gap-10 items-start text-base text-black whitespace-nowrap max-md:max-w-full">
                                        <div>Subtotal:</div>
                                        <div>$1750</div>
                                    </div>
                                    <div className="flex flex-col mt-4 w-full rotate-[8.742277657347563e-8rad]">
                                        <div className="z-10 shrink-0 h-px bg-black border border-black border-solid max-md:max-w-full" />
                                    </div>
                                    <div className="flex gap-10 items-start mt-4 text-base text-black whitespace-nowrap max-md:max-w-full">
                                        <div>Shipping:</div>
                                        <div>Free</div>
                                    </div>
                                    <div className="flex flex-col mt-4 w-full rotate-[8.742277657347563e-8rad]">
                                        <div className="z-10 shrink-0 h-px bg-black border border-black border-solid max-md:max-w-full" />
                                    </div>
                                    <div className="flex gap-10 items-start mt-4 text-base text-black whitespace-nowrap max-md:max-w-full">
                                        <div>Total:</div>
                                        <div>$1750</div>
                                    </div>
                                </div>
                            </div>
                            <PaymentMethod type="Bank" icons={bankIcons} />
                            <PaymentMethod type="Cash on delivery" />

                            <div className="flex flex-wrap gap-4 items-center mt-8">
                                <input
                                    type="text"
                                    placeholder="Coupon Code"
                                    aria-label="Enter coupon code"
                                    className="px-6 py-4 text-black border border-black rounded w-[300px]"
                                />
                                <button className="px-6 py-4 font-medium bg-red-500 text-white rounded">
                                    Apply Coupon
                                </button>
                            </div>

                            <button className="px-12 py-4 mt-8 w-full font-medium bg-red-500 text-white rounded">
                                Place Order
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </main>

    )
}

const PaymentMethod = ({ type, icons }: PaymentMethodProps) => {
    return (
        <div className="flex gap-5 justify-start items-center max-md:max-w-full">
            <input type="radio" name="ddddd" placeholder='dddd' id={type} />
            <label htmlFor={type}>{type}</label>
            {icons && (
                <div className="flex flex-wrap lg:ml-8 items-start self-stretch my-auto">
                    {icons.map((icon, index) => (
                        <img
                            key={index}
                            loading="lazy"
                            src={icon}
                            alt=""
                            className="object-contain shrink-0 aspect-[1.5] w-[72px]"
                        />
                    ))}
                </div>
            )}
        </div>
    );
};

const FormField = ({ label, required = false, id, type = "text" }: FormFieldProps) => {
    return (
        <div className="flex flex-col w-full leading-6">
            <label htmlFor={id} className="opacity-70">
                {label}{required && <span className="text-red-500">*</span>}
            </label>
            <input
                type={type}
                id={id}
                required={required}
                className="flex mt-2 w-full rounded bg-neutral-100 min-h-[50px] px-4"
                aria-required={required}
            />
        </div>
    );
};
export default page
