import { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

export const metadata: Metadata = {
    title: "Login | Giaic Ecommerce Design ",
    description: "Figma to Code Generated by Anas Ahmed for giaic hackhton practice | Login Page",
};


const Page = () => {
    return (
        <div className="flex flex-wrap gap-10 items-center 2xl:justify-between max-md:justify-center self-start mt-14 max-md:mt-10 max-md:max-w-full">
            {/* Image Section */}
            <div className="flex overflow-hidden flex-col self-stretch my-auto rounded-none lg:bg-slate-300 min-w-[240px] max-md:max-w-full w-full lg:w-[calc(60%-20px)] lg:pl-0">
                <Image
                    width={650}
                    height={2000}
                    loading="lazy"
                    src="/auth.png"
                    alt="Sign up illustration"
                    className="object-cover max-lg:hidden aspect-[1.14] w-full h-auto lg:w-scdreen lg:madx-w-none"
                />
            </div>
            {/* Form Section */}
            <div className="flex flex-col 2xl:mr-20 p-4 self-stretch my-auto min-w-[240px] w-full lg:w-[calc(30%-20px)]">
                <div className="flex flex-col self-start text-black">
                    <h1 className="text-3xl font-medium tracking-widest leading-none">
                        Log in to Exclusive
                    </h1>
                    <p className="mt-4 text-base">Enter your details below</p>
                </div>
                <form className="flex flex-col items-center mt-8 max-md:mt-6">
                    <div className="flex flex-col w-full space-y-10">
                        <InputField label="Email or Phone Number" id="email" type="email" />
                        <InputField label="Password" id="password" type="password" />
                    </div>
                    <div className="flex flex-col mt-8 text-base w-full">
                        <div className="flex max-sm:flex-wrap items-center justify-between">
                            <button
                                type="submit"
                                className="gap-2.5 self-stretch w-full py-4 font-medium bg-red-500 rounded text-neutral-50 max-md:px-5"
                            >
                                Log in
                            </button>
                            <button
                                type="button"
                                className="gap-2.5 self-stretch w-full py-4 font-medium text-red-500 rounded max-md:px-5"
                            >
                                Forget Password?
                            </button>
                        </div>
                        <div className="flex flex-col items-center mt-4 text-black">
                            <div className="flex gap-4 items-center mt-8">
                                <span className="self-stretch my-auto opacity-70">
                                    Already have an account?
                                </span>
                                <Link href="/sign-up">
                                    <button className="border-b border-gray-400 self-stretch my-auto font-medium">
                                        <span className="opacity-70">Sign Up</span>
                                    </button>
                                </Link>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    );
};

const InputField: React.FC<InputFieldProps> = ({ label, type = 'text', id }) => {
    return (
        <div className="flex flex-col w-full">
            <label htmlFor={id} className="text-base text-black lg:opacity-40">
                {label}
            </label>
            <div className="flex flex-col mt-2 w-full">
                <input
                    type={type}
                    id={id}
                    name={id}
                    className="w-full border-b px-2 outline-none border-gray-400"
                    aria-label={label}
                />
            </div>
        </div>
    );
};

export default Page;
